data:
  dataset: MNIST
#  dataset: CIFAR100
  zca_whiten: False
  gpu: 0

model:
  seed: 1
  hidden_layer: 1
  batch_size: 5000
  lr: 0.01
  iterations: 30000

distill:
  IPC: 10
  kernel: NNGP
  generate_from_real_data: True